language: generic
env:
  global:
    - CLI_VERSION=latest
matrix:
  include:
    - env:
        - BOARD="arduino:samd:mkr1000"
    - env:
        - BOARD="arduino:samd:mkrwifi1010"
    - env:
        - BOARD="arduino:samd:mkrgsm1400"
    - env:
        - NAME=Spell Check
      language: python
      python: 3.6
      # must define an empty before_install phase, otherwise the default one is used
      before_install: true
      install:
        # https://github.com/codespell-project/codespell
        - pip install codespell
      script:
        - codespell --skip="${TRAVIS_BUILD_DIR}/.git" --ignore-words="${TRAVIS_BUILD_DIR}/extras/codespell-ignore-words-list.txt" "${TRAVIS_BUILD_DIR}"
# default phases
before_install:
  - wget http://downloads.arduino.cc/arduino-cli/arduino-cli-$CLI_VERSION-linux64.tar.bz2
  - tar xf arduino-cli-$CLI_VERSION-linux64.tar.bz2
  - mkdir -p "$HOME/bin"
  - mv arduino-cli $HOME/bin
  - export PATH="$PATH:$HOME/bin"
  - arduino-cli core update-index
  - if [[ "$BOARD" =~ "arduino:samd:" ]]; then
      arduino-cli core install arduino:samd;
    fi
  - buildExampleSketch() { arduino-cli compile --warnings all --fqbn $BOARD $PWD/examples/$1; }
install:
  - mkdir -p $HOME/Arduino/libraries
  - ln -s $PWD $HOME/Arduino/libraries/.
script:
  - buildExampleSketch Arduino_Debug_Basic
notifications:
  webhooks:
    urls:
      - https://www.travisbuddy.com/
    on_success: never
    on_failure: always
